### PR TITLE
Fixed a typo that caused an X11Error on every pressed key

### PR DESCRIPTION
**Pull request by LinusCDE**
The software works great!

However this error prevented me from using it initially.

### CODE REVIEW

**Comment by Evidlo** [comment]
What version of pynput are you on?

```
In [3]: from pynput.keyboard import Key, Controller

In [4]: Key.alt_r
Out[4]: <Key.alt_r: <65514>>
```

**Comment by LinusCDE** [comment]
According to pip my version is 1.4 .

Key.alt_r gets resolved without any problem, however pressing it throws this exception:
```
gTraceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/remarkable_keyboard/mappings.py", line 29, in action                                                          
    self.k.release(Key.alt_r)
  File "/usr/lib/python3.7/site-packages/pynput/keyboard/_base.py", line 410, in release                                                               
    self._handle(resolved, False)
  File "/usr/lib/python3.7/site-packages/pynput/keyboard/_xorg.py", line 207, in _handle                                                               
    dm.keysym_to_keycode(key.vk))
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/lib/python3.7/site-packages/pynput/_util/xorg.py", line 78, in display_manager                                                            
    raise X11Error(errors)
pynput._util.xorg.X11Error: [(BadValue(<Xlib.display._BaseDisplay object at 0x7f04f6ecf400>, b'\x00\x023\x00\x00\x00\x00\x00\x02\x00\x84\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'), None)]                                                                         
X11Error for key g
```
The key (g in this case) gets pressed (first letter in stacktrace), but releasing Key.alt_r doesn't work.

(Same exception when running `Controller().press(Key.alt_r)` in the python (3) repl)

**Comment by Evidlo** [comment]
I don't seem to have any problem with `alt_r`

```
In [4]: k = Controller()

In [5]: k.press(Key.alt_r);k.press('g');k.release(Key.alt_r)
^[g
```

**Comment by LinusCDE** [comment]
Then it seems to be a platform dependant issue.
I'm using KDE Plasma on Arch.

May computer (ASUS laptop) doesn't seem to recognize the keycode for alt_r.

```
Python 3.7.2 (default, Jan 10 2019, 23:51:51)
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pynput.keyboard import Key, Controller
>>> k = Controller()
>>> k.press(Key.alt_r)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/pynput/keyboard/_base.py", line 377, in press
    self._handle(resolved, True)
  File "/usr/lib/python3.7/site-packages/pynput/keyboard/_xorg.py", line 207, in _handle
    dm.keysym_to_keycode(key.vk))
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/lib/python3.7/site-packages/pynput/_util/xorg.py", line 78, in display_manager
    raise X11Error(errors)
pynput._util.xorg.X11Error: [(BadValue(<Xlib.display._BaseDisplay object at 0x7efdc01e1a58>, 
b'\x00\x02\x0f\x00\x00\x00\x00\x00\x02\x00\x84\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'), None)]
>>> k.press('g')
>>> k.release(Key.alt_r)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/pynput/keyboard/_base.py", line 410, in release
    self._handle(resolved, False)
  File "/usr/lib/python3.7/site-packages/pynput/keyboard/_xorg.py", line 207, in _handle
    dm.keysym_to_keycode(key.vk))
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/lib/python3.7/site-packages/pynput/_util/xorg.py", line 78, in display_manager
    raise X11Error(errors)
pynput._util.xorg.X11Error: [(BadValue(<Xlib.display._BaseDisplay object at 0x7efdc01e1a58>, 
b'\x00\x02\x16\x00\x00\x00\x00\x00\x02\x00\x84\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'), None)]
>>>
```

**Pull request closed without merging**
